main: com.tyrellplayz.servermail.ServerMail
name: ServerMail
version: 0.1.0
website: http://www.youtube.com/legotyrell
author: TyrellPlayz
description: ServerMail is a gui based mail system for a spigot server which allows players to send messages to online and offline players.
softdepend: [ProtocolLib]
commands:
    mail:
        description: Opens the mail gui
        permission: servermail.mail
        permissionMessage: You need the right permission to use this command
        usage: <command>
    maildisable:
        description: Disables the players mail so they can't recieve any mail
        permission: servermail.disable
        permissionMessage: You need the right permission to use this command
        usage: <command>
    deletemail:
        description: Delete a mail. Used from book meassage
        permission: servermail.mail
        permissionMessage: You need the right permission to use this command
        usage: <command>
    replymail:
        description: Reply to a mail. Used from book meassage
        permission: servermail.mail
        permissionMessage: You need the right permission to use this command
        usage: <command>

permissions:
    servermail.mail:
        description: Allows a player access to /mail
    servermail.disable:
        description: Allows a player disable their mail